#!/bin/bash

# auth v1 request

echo "curl -i -H \"X-Auth-User: test:tester\" -H \"X-Auth-Key: testing\" http://saio:8080/auth/v1.0"
curl -i -H "X-Auth-User: test:tester" -H "X-Auth-Key: testing" http://saio:8080/auth/v1.0
