#!/bin/bash

# dynamic manifest

. ./get_token

echo "create container c2"
curl -i -H "X-Auth-Token: $TOKEN" http://saio:8080/v1/AUTH_test/c2 -XPUT

echo "curl -i -H \"X-Auth-Token: $TOKEN\" http://saio:8080/v1/AUTH_test/c2/dynamic_large -XPUT -H \"Content-Length: 0\" -H \"X-Object-Manifest: c/a/\""
curl -i -H "X-Auth-Token: $TOKEN" http://saio:8080/v1/AUTH_test/c2/dynamic_large -XPUT -H "Content-Length: 0" -H "X-Object-Manifest: c/a/"


echo "read the dynamic large object manifest"
curl -i -H "X-Auth-Token: $TOKEN" http://saio:8080/v1/AUTH_test/c2/dynamic_large
